create table if not exists public.cabins (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  "maxCapacity" integer not null,
  "regularPrice" numeric not null,
  discount numeric not null default 0,
  description text not null,
  image text not null
);

insert into public.cabins (
  id,
  name,
  "maxCapacity",
  "regularPrice",
  discount,
  description,
  image
)
values
  (
    1,
    '001',
    2,
    250,
    0,
    'Discover the ultimate luxury getaway for couples in the cozy wooden cabin 001. Nestled in a picturesque forest, this stunning cabin offers a secluded and intimate retreat. Inside, enjoy modern high-quality wood interiors, a comfortable seating area, a fireplace and a fully-equipped kitchen. The plush king-size bed, dressed in fine linens guarantees a peaceful nights sleep. Relax in the spa-like shower and unwind on the private deck with hot tub.',
    '/cabins/cabin-001.jpg'
  ),
  (
    2,
    '002',
    2,
    350,
    25,
    'Escape to the serenity of nature and indulge in luxury in our cozy cabin 002. Perfect for couples, this cabin offers a secluded and intimate retreat in the heart of a picturesque forest. Inside, you will find warm and inviting interiors crafted from high-quality wood, a comfortable living area, a fireplace and a fully-equipped kitchen. The luxurious bedroom features a plush king-size bed and spa-like shower. Relax on the private deck with hot tub and take in the beauty of nature.',
    '/cabins/cabin-002.jpg'
  ),
  (
    3,
    '003',
    4,
    300,
    0,
    'Experience luxury family living in our medium-sized wooden cabin 003. Perfect for families of up to 4 people, this cabin offers a comfortable and inviting space with all modern amenities. Inside, you will find warm and inviting interiors crafted from high-quality wood, a comfortable living area, a fireplace, and a fully-equipped kitchen. The bedrooms feature plush beds and spa-like bathrooms. The cabin has a private deck with a hot tub and outdoor seating area, perfect for taking in the natural surroundings.',
    '/cabins/cabin-003.jpg'
  ),
  (
    4,
    '004',
    4,
    500,
    50,
    'Indulge in the ultimate luxury family vacation in this medium-sized cabin 004. Designed for families of up to 4, this cabin offers a sumptuous retreat for the discerning traveler. Inside, the cabin boasts of opulent interiors crafted from the finest quality wood, a comfortable living area, a fireplace, and a fully-equipped gourmet kitchen. The bedrooms are adorned with plush beds and spa-inspired en-suite bathrooms. Step outside to your private deck and soak in the natural surroundings while relaxing in your own hot tub.',
    '/cabins/cabin-004.jpg'
  ),
  (
    5,
    '005',
    6,
    350,
    0,
    'Enjoy a comfortable and cozy getaway with your group or family in our spacious cabin 005. Designed to accommodate up to 6 people, this cabin offers a secluded retreat in the heart of nature. Inside, the cabin features warm and inviting interiors crafted from quality wood, a living area with fireplace, and a fully-equipped kitchen. The bedrooms are comfortable and equipped with en-suite bathrooms. Step outside to your private deck and take in the natural surroundings while relaxing in your own hot tub.',
    '/cabins/cabin-005.jpg'
  ),
  (
    6,
    '006',
    6,
    800,
    100,
    'Experience the epitome of luxury with your group or family in our spacious wooden cabin 006. Designed to comfortably accommodate up to 6 people, this cabin offers a lavish retreat in the heart of nature. Inside, the cabin features opulent interiors crafted from premium wood, a grand living area with fireplace, and a fully-equipped gourmet kitchen. The bedrooms are adorned with plush beds and spa-like en-suite bathrooms. Step outside to your private deck and soak in the natural surroundings while relaxing in your own hot tub.',
    '/cabins/cabin-006.jpg'
  ),
  (
    7,
    '007',
    8,
    600,
    100,
    'Accommodate your large group or multiple families in the spacious and grand wooden cabin 007. Designed to comfortably fit up to 8 people, this cabin offers a secluded retreat in the heart of beautiful forests and mountains. Inside, the cabin features warm and inviting interiors crafted from quality wood, multiple living areas with fireplace, and a fully-equipped kitchen. The bedrooms are comfortable and equipped with en-suite bathrooms. The cabin has a private deck with a hot tub and outdoor seating area, perfect for taking in the natural surroundings.',
    '/cabins/cabin-007.jpg'
  ),
  (
    8,
    '008',
    10,
    1400,
    0,
    'Experience the epitome of luxury and grandeur with your large group or multiple families in our grand cabin 008. This cabin offers a lavish retreat that caters to all your needs and desires. The cabin features an opulent design and boasts of high-end finishes, intricate details and the finest quality wood throughout. Inside, the cabin features multiple grand living areas with fireplaces, a formal dining area, and a gourmet kitchen that is a chef''s dream. The bedrooms are designed for ultimate comfort and luxury, with plush beds and en-suite spa-inspired bathrooms. Step outside and immerse yourself in the beauty of nature from your private deck, featuring a luxurious hot tub and ample seating areas for ultimate relaxation and enjoyment.',
    '/cabins/cabin-008.jpg'
  )
on conflict (id) do update
set
  name = excluded.name,
  "maxCapacity" = excluded."maxCapacity",
  "regularPrice" = excluded."regularPrice",
  discount = excluded.discount,
  description = excluded.description,
  image = excluded.image;

select setval(
  pg_get_serial_sequence('public.cabins', 'id'),
  coalesce((select max(id) from public.cabins), 1),
  true
);
