create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "fullName" text not null,
  email text not null unique,
  nationality text not null,
  "nationalID" text not null unique,
  "countryFlag" text not null
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "startDate" date not null,
  "endDate" date not null,
  "numNights" integer not null check ("numNights" > 0),
  "numGuests" integer not null check ("numGuests" > 0),
  "cabinPrice" numeric not null check ("cabinPrice" >= 0),
  "extrasPrice" numeric not null default 0 check ("extrasPrice" >= 0),
  "totalPrice" numeric not null check ("totalPrice" >= 0),
  status text not null check (status in ('unconfirmed', 'checked-in', 'checked-out')),
  "hasBreakfast" boolean not null default false,
  "isPaid" boolean not null default false,
  observations text not null default '',
  "cabinId" bigint not null references public.cabins (id) on delete cascade,
  "guestId" bigint not null references public.guests (id) on delete cascade
);

insert into public.guests (
  id,
  "fullName",
  email,
  nationality,
  "nationalID",
  "countryFlag"
)
values
  (
    1,
    'Jonathan Smith',
    'johnsmith@test.eu',
    'Great Britain',
    '4534593454',
    'https://flagcdn.com/gb.svg'
  ),
  (
    2,
    'Emma Watson',
    'emma.watson@example.com',
    'United Kingdom',
    '1234578901',
    'https://flagcdn.com/gb.svg'
  ),
  (
    3,
    'Maria Rodriguez',
    'maria.rodriguez@example.com',
    'Spain',
    '1098765321',
    'https://flagcdn.com/es.svg'
  ),
  (
    4,
    'John Doe',
    'john.doe@example.com',
    'United States',
    '3245908744',
    'https://flagcdn.com/us.svg'
  ),
  (
    5,
    'David Smith',
    'david.smith@example.com',
    'Australia',
    '44450960283',
    'https://flagcdn.com/au.svg'
  ),
  (
    6,
    'Julie Nguyen',
    'julie.nguyen@example.com',
    'Vietnam',
    '5678901234',
    'https://flagcdn.com/vn.svg'
  )
on conflict (id) do update
set
  "fullName" = excluded."fullName",
  email = excluded.email,
  nationality = excluded.nationality,
  "nationalID" = excluded."nationalID",
  "countryFlag" = excluded."countryFlag";

insert into public.bookings (
  id,
  created_at,
  "startDate",
  "endDate",
  "numNights",
  "numGuests",
  "cabinPrice",
  "extrasPrice",
  "totalPrice",
  status,
  "hasBreakfast",
  "isPaid",
  observations,
  "cabinId",
  "guestId"
)
values
  (
    1,
    now() - interval '20 days',
    current_date,
    current_date + 7,
    7,
    2,
    1750,
    210,
    1960,
    'unconfirmed',
    true,
    false,
    'Please prepare a gluten-free breakfast.',
    1,
    1
  ),
  (
    2,
    now() - interval '35 days',
    current_date - 14,
    current_date - 10,
    4,
    2,
    1400,
    0,
    1400,
    'checked-out',
    false,
    true,
    '',
    2,
    2
  ),
  (
    3,
    now() - interval '8 days',
    current_date - 2,
    current_date + 3,
    5,
    4,
    1500,
    300,
    1800,
    'checked-in',
    true,
    true,
    'Late arrival after 22:00.',
    3,
    3
  ),
  (
    4,
    now() - interval '3 days',
    current_date + 10,
    current_date + 15,
    5,
    4,
    2500,
    300,
    2800,
    'unconfirmed',
    true,
    false,
    '',
    4,
    4
  ),
  (
    5,
    now() - interval '12 days',
    current_date + 5,
    current_date + 8,
    3,
    5,
    1050,
    225,
    1275,
    'unconfirmed',
    true,
    true,
    'One guest has a peanut allergy.',
    5,
    5
  ),
  (
    6,
    now() - interval '2 days',
    current_date + 18,
    current_date + 25,
    7,
    6,
    5600,
    0,
    5600,
    'unconfirmed',
    false,
    false,
    'Quiet cabin preferred if possible.',
    6,
    6
  )
on conflict (id) do update
set
  created_at = excluded.created_at,
  "startDate" = excluded."startDate",
  "endDate" = excluded."endDate",
  "numNights" = excluded."numNights",
  "numGuests" = excluded."numGuests",
  "cabinPrice" = excluded."cabinPrice",
  "extrasPrice" = excluded."extrasPrice",
  "totalPrice" = excluded."totalPrice",
  status = excluded.status,
  "hasBreakfast" = excluded."hasBreakfast",
  "isPaid" = excluded."isPaid",
  observations = excluded.observations,
  "cabinId" = excluded."cabinId",
  "guestId" = excluded."guestId";

select setval(
  pg_get_serial_sequence('public.guests', 'id'),
  coalesce((select max(id) from public.guests), 1),
  true
);

select setval(
  pg_get_serial_sequence('public.bookings', 'id'),
  coalesce((select max(id) from public.bookings), 1),
  true
);
